language: node_js
node_js:
- 10
branches:
  only:
  - main
cache:
  directories:
  - node_modules
before_script:
- npm i firebase-tools -g
script:
- npm install
- npm run build
- firebase deploy --only hosting --token $FIREBASE_TOKEN