export const  ADD_NEW_DEATH_CAUSE = 'ADD_NEW_DEATH_CAUSE';
export const GET_ALL_DEATHS = 'GET_ALL_DEATHS';
export const UPDATE_DEATH_COUNT = 'UPDATE_DEATH_COUNT';
export const DELETE_DEATH_CAUSE = 'DELETE_DEATH_CAUSE';
export const SET_LOADING = 'SET_LOADING';
export const SET_INITIAL_LOAD_ERROR = 'SET_INITIAL_LOAD_ERROR';